var accomodation = '<a href= "" class = "title_id accomodation col-10 col-xl-8 mt-3 p-5" data-id="{{id}}">'
    + '<div class="row">'
    + '<div class="col-12 col-xl-5">'
    + '<img src="{{image}}">'
    + '</div>'
    + '<div class="col-12 col-xl-5">'
    + '<h4>{{title}}<h4>'
    + '<h5 class = "mt-6"> {{streetaddress}} {{streetnumber}}, {{neighbourhood}}</h5>'
    + '<p>{{description}}</p>'
    + '<div class = "row justify-content-center">'
    + '<div class="col-6 col-xl-6 headline_startdate">'
    + '<b>Tidigast inflytt</b>'
    + '</div>'
    + '<div class="col-6 col-xl-6 headline_enddate">'
    + '<b>Senast utflytt</b>' 
    + '</div>'
    + '</div>'
    + '<div class = "row justify-content-center">'
    + '<div class = "col-6 col-xl-6 read_more_startdate"> '
    + '<p> {{startdate}} </p>'
    + '</div>'
    + '<div class ="col-6 col-xl-6 read_more_enddate"> '
    + '<p> {{enddate}}</p>'
    + '</div>'
    + '</div>'
    + '</div>'
    + '<div class="col-12 col-xl-2">'
    + '<div class="row justify-content-center"'
    + '<div class="col-4 col-xl-12 ">'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<i class="fas fa-home"></i>'
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<b>{{squaremetres}} kvm </b>' 
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<i class="fas fa-building"></i>' 
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<b> {{accommodationtype}} </b>'
    + '</div>'
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<h4>  {{price}} kr </h4>'
    + '</div>'
    + '</div>'
    + '</div>'
    + '</div>'
    + '</a>';

var my_accomodation = '<div class="my_accomodation col-9 mt-3 p-2">'
    + '<div class="row">'
    + '<div class="col-12 col-xl-5">'
    + '<img src="{{image}}">'
    + '</div>'
    + '<div class="col-12 col-xl-5">'
    + '<h4>{{title}}<h4>'
    + '<h5 class = "mt-6"> {{streetaddress}} {{streetnumber}}, {{neighbourhood}}</h5>'
    + '<p>{{description}}</p>'
    + '<div class = "row justify-content-center">'
    + '<div class="col-6 col-xl-6 headline_startdate">'
    + '<b>Tidigast inflytt</b>'
    + '</div>'
    + '<div class="col-6 col-xl-6 headline_enddate">'
    + '<b>Senast utflytt</b>' 
    + '</div>'
    + '</div>'
    + '<div class = "row justify-content-center">'
    + '<div class = "col-6 col-xl-6 read_more_startdate"> '
    + '<p> {{startdate}} </p>'
    + '</div>'
    + '<div class ="col-6 col-xl-6 read_more_enddate"> '
    + '<p> {{enddate}}</p>'
    + '</div>'
    + '</div>'
    + '</div>'
    + '<div class="col-12 col-xl-2">'
    + '<div class="row justify-content-center"'
    + '<div class="col-4 col-xl-12 ">'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<i class="fas fa-home"></i>'
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<b>{{squaremetres}} kvm </b>' 
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<i class="fas fa-building"></i>' 
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<b> {{accommodationtype}} </b>'
    + '</div>'
    + '</div>'
    + '<div class="col-2 col-xl-12 search_page_price">'
    + '<h4>  {{price}} kr </h4>'
    + '</div>'
    + '</div>'
    + '</div>'
    + '</div>';

var tenant = '<div class="my_tenant col-2 offset-1 mt-3 p-2">'
    + '<h1>{{name}}</h1>'
    + '<button type="button" class="book_ad_button" data-id="{{ad_id}}">Godkänn</button>'
    + '<button type="button" class="deny_ad_button" data-id="{{ad_id}}">Neka</button>'
    + '</div>';